version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/webapp-ui
permissions:
  - object: /
    owner: root
    group: root
hooks:
  BeforeInstall:
    - location: codedeploy/beforeInstall.sh
      timeout: 1000
      runas: root
  AfterInstall:
    - location: codedeploy/afterInstall.sh
      timeout: 1000
      runas: root
  ApplicationStart:
    - location: codedeploy/applicationStart.sh
      timeout: 1000
      runas: root
 